"""empty message

Revision ID: 64125d1049c4
Revises: 765d0dde999b
Create Date: 2026-03-20 16:18:02.421398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64125d1049c4'
down_revision = '765d0dde999b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_tool', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_api_tool_account_id'))
        batch_op.drop_index(batch_op.f('idx_api_tool_provider_id_name'))

    with op.batch_alter_table('api_tool_provider', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_api_tool_provider_account_id'))
        batch_op.drop_constraint(batch_op.f('uk_api_tool_provider_account_id_name'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_tool_provider', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uk_api_tool_provider_account_id_name'), ['account_id', 'name'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_api_tool_provider_account_id'), ['account_id'], unique=False)

    with op.batch_alter_table('api_tool', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_api_tool_provider_id_name'), ['provider_id', 'name'], unique=False)
        batch_op.create_index(batch_op.f('idx_api_tool_account_id'), ['account_id'], unique=False)

    # ### end Alembic commands ###
